name: Pareto CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-test-suites:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use pnpm package manager
        uses: pnpm/action-setup@v2.0.1

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: 16   
          cache: 'pnpm'

      - name: Install dependencies   
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:unit

      - name: Launch server and run integration tests
        run: |
          pnpm run start &
          sleep 15 &&
          curl http://localhost:3000 &&
          pnpm test:integration
